---
title: "00_DataVisualization"
author: "Denizard"
date: "2025-03-05"
output: html_document
---

######################################### 
#                                       #
#    GMA Project - Data Visualization   #
#                                       # 
######################################### 

## Raw data visualization

# Principal Component Analysis

```{r}
load("./data/PlotData.RData")
library(compositions)

plot(pcx, type = "screeplot", main = 'Scree plot Main Phenotypic Traits')
detach("package:compositions", unload = TRUE)
```

# Irrigation uniformity interpolation

```{r}
load("./data/PlotData.RData")

# postscript("figures/irrig.idw.eps", height = 6, width = 3)  # Width/height in inches
# sp::spplot(irrig.idw, zcol = "var1.pred")
# dev.off()
sp::spplot(irrig.idw, zcol = "var1.pred")
```

# Correlation of Irrigation Flow and Trait

```{r}
load("./data/MeansTable.RData")
library(ggplot2)

traits <- read.csv("traitsGLMMres.csv", header = TRUE, encoding = "UTF-8")
colors <- c("yellow", "skyblue", "red", "lightgreen", "hotpink", "purple1")  # Distinct colors

df <- df_tot

plots <- list()
for (i in 1:nrow(traits)) {

  plots[[i]] <- ggplot(
    df,
    aes_string(x = paste0("value_", traits$abrv[i]), y = "irr_flw")
  ) +
  geom_point(aes(fill = generation), shape = 23, alpha = 0.6, size = 2) +
  geom_smooth(method = "glm", se = TRUE) +
  scale_fill_manual(values = colors, name = "Gen") +
  labs(
       x = latex2exp::latex2exp::TeX(traits$name[i]),
       y = latex2exp::latex2exp::TeX("Irrigation Flow ($mm.h^{-1}$)")
       ) +
  ggpubr::stat_cor(aes(label = ..rr.label..),
                   label.x.npc = "left",
                   label.y.npc = "top",
                   digits = 3) +
  theme(legend.position = "right")

  plot(plots[[i]])
}

# postscript("figures/irrcv.eps")
# do.call(grid.arrange, c(plots, ncol = 5, nrow = 3))
# dev.off()
detach("package:ggplot2", unload = TRUE)
```


# Box-Cox of trait data
```{r}
load("./data/MeansTable.RData")

traits <- read.csv("traitsGLMMres.csv", header = TRUE, encoding = "UTF-8")
# pdf("figures/boxcox.pdf", width=12, height=8)

# set a 3‑row by 5‑column grid for base‑R plots
def_par <- par(mfrow = c(3, 5), mar = c(4, 4, 2, 1))
on.exit(par(def_par))

for (i in 1:nrow(traits)) {
  # pull out the vector, add a tiny constant
  x <- na.omit(df_tot[[paste0("value_", traits$abrv[i])]]) + 1e-4
  
  # draw the base‑R Box–Cox plot
  MASS::boxcox(
    sqrt(x^2) ~ 1,
    data  = data.frame(x = x),
    xlab  = latex2exp::latex2exp::TeX(paste0("Lambda \\lambda ", traits$name[i]))
  )
}

# dev.off()
```

# Boxlot of Means and Std Errors

```{r}
load("./data/MeansTable.RData")
library(tidyverse)

traits <- read.csv("traitsGLMMres.csv", header = TRUE, encoding = "UTF-8")
colors <- c("yellow", "skyblue", "red", "lightgreen", "hotpink", "purple1")

plots <- list()
for (i in 1:nrow(traits)){

	vsr <- c("value", "solution", "res")
	old <- paste(vsr, traits$abrv[i], sep = "_")

	# Perform two left joins and coalesce the results
	df <- df_tot |>
		select(c(names(df_names), all_of(old))) |> 
		rename_with(~ vsr, all_of(old)) |>
		mutate(solution = if_else(
					  generation %in% c("P1", "P2", "F1"),
					  solution + res,
					  solution)) |>
		pivot_longer(c(value, solution)) |> 
		mutate(name = factor(name,
				     levels = c("value", "solution"),
				     labels = c("Raw", "BLUEs")))

	# Basic box plot
	plots[[i]] <- ggplot(df, aes(x = generation, y = value,
			    fill = generation, color = name), 
		    na.rm = TRUE) +
		geom_boxplot(alpha = 0.6, position = position_dodge(0.9)) +
		scale_fill_manual(values = colors) +
		scale_color_manual(values = c("black", "darkgrey")) +
		labs(
		     title = latex2exp::TeX(traits$name[i]),
		     color = "Dataset",
		     fill = "Generation",
		     x = NULL,
		     y = NULL
		     # y = latex2exp::TeX(traits$name[i])
		     ) +
		# theme_minimal() +
		scale_x_discrete(limits=c("BC2","BC1","F2","F1","P2","P1")) +
		theme(
		      axis.text.y = element_blank(),  # Remove x-axis tick labels
		      axis.ticks.y = element_blank()  # Remove x-axis ticks
		      ) +
		coord_flip() 

  plot(plots[[i]])
}

# postscript(paste0("figures/variances_tot.eps"))
# do.call(grid.arrange, c(plots, ncol = 5, nrow = 3))
# dev.off()
detach("package:tidyverse", unload = TRUE)
```

```{r}
load("./data/MeansTable.RData")
library(ggplot2)

# Iterate over each trait to create histograms with normal distribution curves
traits <- read.csv("traitsGLMMres.csv", header = TRUE, encoding = "UTF-8")

plots <- list()
for (i in 1:nrow(traits)) {
	name <- traits$name[i]  # Descriptive name for the current trait

	# Create the plot
	plots[[i]] <- ggplot(df_tot, aes_string(x = paste0("value_", traits$abrv[i]))) +
		geom_histogram(aes(y = ..density..),
			       binwidth = 1, 
			       fill = "lightgray", 
			       color = "white", 
			       na.rm = TRUE) +
		geom_density(aes(y = ..density..),
			     color = "blue",
			     lwd = 1,
			     na.rm = TRUE) +
		facet_wrap(~generation, ncol = 1, scales = "free_y") +
		labs(
		     title = paste("Distribution of", name, "by Generation"),
		     x = name,
		     y = "Density"
		     ) +
		theme_minimal() +
		theme(legend.position = "top")

	# Display the plot
	plot(plots[[i]])
}

detach("packages:ggplot2", unload = TRUE)
```

```{r}
load("./data/MeansTable.RData")

df <- df_tot

traits <- read.csv("traitsGLMMres.csv", header = TRUE, encoding = "UTF-8")
colors <- c("yellow", "skyblue", "red", "lightgreen", "hotpink", "purple1")

def_par <- par(mfrow = c(3, 5), mar = c(4, 4, 2, 1))
on.exit(par(def_par))

for (i in 1:nrow(traits)){
  abrv <- paste0("value_", traits$abrv[i])

	# Calculate densities and find max density for ylim adjustment
	densities <- lapply(split(df[[abrv]], df$generation), density, na.rm = TRUE)
	max_density <- max(sapply(densities, function(d) max(d$y)))

	# Create an empty histogram with adjusted ylim

	hist(df[[abrv]], 
	     # main = paste0("Normal fit of ", tolower(traits$name[i]), " by generation"), 
	     # xlab = traits$name[i], 
	     main = "",
	     xlab = "",
	     ylab = "Density", 
	     freq = FALSE,             # Plot density instead of counts
	     col = "lightgray",        # Light background for clarity
	     border = "white",         # Remove bar borders
	     ylim = c(0, max_density + 0.025))  # Set ylim based on max density

	# Add legend
	# legend("topright", legend = levels(df$generation), col = colors, lwd = 2, title = "Generation")

	# Add normal distribution fit lines
	mean_val <- mean(df[[abrv]], na.rm = TRUE)    # Mean of the group
	sd_val <- sd(df[[abrv]], na.rm = TRUE)        # Standard deviation of the group

	curve(dnorm(x, mean = mean_val, sd = sd_val),  # Normal curve
	      lwd = 2, add = TRUE)

	for (j in unique(df$generation)) {
		group_data <- df[[abrv]][df$generation == j]
		mean_val <- mean(group_data, na.rm = TRUE)    # Mean of the group
		sd_val <- sd(group_data, na.rm = TRUE)        # Standard deviation of the group

		curve(dnorm(x, mean = mean_val, sd = sd_val),  # Normal curve
		      col = colors[which(unique(df$generation) == j)],
		      lwd = 2, add = TRUE)
	}

	# Add legend
	legend("topright", legend = levels(as.factor(df$generation)), col = colors, lwd = 2, title = "Generation")
}
```

##ASReml Outputs

#Residuals Model
```{r}
load("./data/modelsGLMMs.RData")

traits <- read.csv("traitsGLMMres.csv", header = TRUE, encoding = "UTF-8")

# pdf(paste0("figures/res_tot.pdf"))
for (i in 1:nrow(traits)){

  abrv <- traits$abrv[i]
  t <- traits$trait[i]
  f <- traits$fam[i]
  j <- traits$mod[i]

  # pdf(paste0("figures/res_", abrv,".pdf"))
  # postscript(paste0("figures/residual_", t, ".eps"), width = 6, height = 6)
  # for(j in 1:length(mods)){
    asr <- paste(abrv, f, sprintf("%02d",j), "tom.asr", sep = "_")

    asrfam <-switch(f,
      "asr_gaussian(link = 'identity', dispersion = NA)",
      "asr_gaussian(link = 'log', dispersion = NA)",
      "asr_poisson(link = 'identity', dispersion = NA)",
      "asr_poisson(link = 'log', dispersion = NA)",
      "asr_poisson(link = 'sqrt', dispersion = NA)")

    tryCatch({
      plot(asremls[[asr]]$model)
    }, error = function(e) {
        message("Error at trait ", t, ", model ", j, ": ", conditionMessage(e))
      })
  # }
  # dev.off()
}
# dev.off()
# plot(asremls[[asr]]$model)
```

#Variograms
```{r}
load("./data/modelsGLMMs.RData")

traits <- read.csv("traitsGLMMres.csv", header = TRUE, encoding = "UTF-8")

# pdf(paste0("figures/vario_tot.pdf"))
for (i in 1:nrow(traits)){
# for (i in c(7,9,10,13,14)){
	
	abrv <- traits$abrv[i]
	t <- traits$trait[i]
	f <- traits$fam[i]
	j <- traits$mod[i]
	name <- traits$name[i]
  
	# png(paste0("figures/varioG_", abrv,".png"), bg = "transparent",
	#     width = 15,
	#     height = 15,
	#     units = "cm",
	#     res = 1200)
	# pdf(paste0("figures/varioG_", abrv,".pdf"))
	# postscript(paste0("figures/variogram_", t, ".eps"), width = 6, height = 6)
	# for(j in 1:length(mods)){
	asr <- paste(abrv, f, sprintf("%02d",j), "tom.asr", sep = "_")

	asrfam <-switch(traits$fam[i],
			"asr_gaussian(link = 'identity', dispersion = NA)",
			"asr_gaussian(link = 'log', dispersion = NA)",
			"asr_poisson(link = 'identity', dispersion = NA)",
			"asr_poisson(link = 'log', dispersion = NA)",
			"asr_poisson(link = 'sqrt', dispersion = NA)")

	tryCatch({
    plot(asreml::varioGram(asremls[[asr]]$model), main = latex2exp::TeX(paste(name)))
	}, error = function(e) {
		message("Error at trait ", t, ", model ", j, ": ", conditionMessage(e))
	})
	# }
	# dev.off()
}
# dev.off()
# plot(varioGram(asremls[[asr]]$model))
```


#GMA A+D models
```{r}
load("./data/modelsGLMMs.RData")

traits <- read.csv("traitsGLMMres.csv", header = TRUE, encoding = "UTF-8")

traitsEPI <- traits |> filter(trait %in% c(
  "num_sideshoot",
  "total_leaf_sideshoot",
  "sideshoot_length"
))

traitsAD <- setdiff(traits, traitsEPI)

plots <- list()




```


#GMA A+D models
```{r}
traitsEPI <- traits |> filter(trait %in% c(
  "num_sideshoot",
  "total_leaf_sideshoot",
  "sideshoot_length"
))

traitsAD <- setdiff(traits, traitsEPI)

plots <- list()

for (i in 1:nrow(traitsAD)) {

i <- 1
  abrv <- traitsAD$abrv[i]
  name <- traitsAD$name[i]
  
  # build gma and compute x & y
  gma <- gma_list[[abrv]]
  gma <- gma_list[[abrv]] |>
    filter(model != "epi") |>
    select(Dataset, parameters, estimates) |>
    mutate(Dataset = factor(Dataset,
                            levels = levels(gma_list[[abrv]]$Dataset),
                            labels = c("Raw", "BLUEs"))) |> 
    pivot_wider(names_from = "parameters", values_from = "estimates") |>
    mutate(
      x_left  = mhat - ahat,
      x_mid   = mhat,
      x_right = mhat + ahat,
      x_extra = mhat + dhat,
      y       = c(1, 0)
    )
  
  df_lines <- gma |> select(Dataset, x_left, x_right, x_extra, y)
  df_ticks <- gma |>
    pivot_longer(
      cols      = c(x_left, x_mid, x_right, x_extra),
      names_to  = "tick",
      values_to = "x"
    ) |>
    mutate(
      lower = case_when(
        tick == "x_left"  ~ "m-a",
        tick == "x_mid"   ~ "m",
        tick == "x_right" ~ "m+a",
        tick == "x_extra" ~ "m+d"
      ),
      upper = case_when(
        tick == "x_left"  ~ "AA",
        tick == "x_mid"   ~ "u",
        tick == "x_right" ~ "BB",
        tick == "x_extra" ~ "AB"
      )
    )
  
  y_breaks <- df_lines$y
  y_labels <- df_lines$Dataset
  ord      <- order(y_breaks)
  y_breaks <- y_breaks[ord]
  y_labels <- y_labels[ord]
  
  plots[[i]] <- ggplot() +
  ggplot() +
    geom_segment(
      data = df_lines,
      aes(x = x_left, xend = x_extra, y = y, yend = y),
      size = 0.35,
      color = "red"
    ) +
    geom_segment(
      data = df_lines,
      aes(x = x_left, xend = x_right, y = y, yend = y),
      size = 0.5
    ) +
    geom_segment(
      data = df_ticks,
      aes(x = x, xend = x, y = y - 0.05, yend = y + 0.05),
      size = 0.5
    ) +
    ggrepel::geom_text_repel(
      data = df_ticks,
      aes(x = x, y = y - 0.25, label = lower),
      size = 4,
      direction = "y",
      nudge_y = -0.1,
      segment.color = NA,
      min.segment.length = 0,
      fontface = "bold"
    ) +
    ggrepel::geom_text_repel(
      data = df_ticks,
      aes(x = x, y = y + 0.25, label = upper),
      size = 4,
      direction = "y",
      nudge_y = 0.1,
      segment.color = NA,
      min.segment.length = 0,
      fontface = "bold"
    ) +
    scale_y_continuous(
      name = NULL,
      breaks = y_breaks,
      labels = y_labels
    ) +
    scale_x_continuous(
      expand = expansion(add = c(0.1 * diff(range(df_ticks$x)), 0))
    ) +
    theme_minimal() +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(size = 10),
      axis.text.y = element_text(size = 11),
      axis.ticks.x = element_line(color = "gray80"),
      panel.grid.major.x = element_line(color = "gray90"),
      panel.grid.major.y = element_blank(),
      plot.title = element_text(hjust = 0.5)
    )
    # ggtitle(latex2exp::TeX(paste("Additive + dominance model of", tolower(name))))
    # ggtitle(latex2exp::TeX(paste(name)))

 	# png(paste0("figures/ruler_", abrv,".png"), bg = "transparent",
 	#     width = 15,
 	#     height = 15,
 	#     units = "cm",
 	#     res = 1200)
  # postscript(paste0("figures/ruler_", abrv, ".eps"), width = 6, height = 4)
  plot(plots[[i]])
  # dev.off()

}

# plot(plots[[i]])

# postscript("figures/ad.eps")
# do.call(grid.arrange, c(plots, ncol = 4, nrow = 3))
# dev.off()

```

